config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
 # resources :twitter do
  #  post :train2, :on => :collection
	#end
	root :to => "trainer#index"
	get '/t_initial', to: 'trainer#t_initial'
  get '/trainer_correct', to: 'trainer#inp_train'
  get '/train_txt', to: 'trainer#train_txt'
  get '/direct', to: 'trainer#index'



	get '/123', to:  'twitter#index'
  get '/twitter', to: 'twitter#new'
  get '/send', to: 'twitter#update'
  get '/show', to: 'twitter#show'
  get '/train', to: 'twitter#train'
  get '/check', to: 'twitter#check' 
  get '/initial', to: 'twitter#initial'
  get '/train2', to: 'twitter#train2'
  get '/train3', to: 'twitter#index'
  get '/trninp', to: 'twitter#inp_train'
  get '/after_train', to: 'twitter#train2_index'


end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController

	def train_txt 

		content = ''
			File.open('training_set.txt', 'r') do |file|
 			content = file.read
		end

		training_set = content.split("\n")
		categories   = training_set.shift.split(',').map{|c| c.strip}

		classifier1 = ClassifierReborn::Bayes.new categories

		training_set.each do |a_line|
  		next if a_line.empty? || '#' == a_line.strip[0]
  		parts = a_line.strip.split(':')
  		classifier1.train(parts.first, parts.last)
		end

		classifier_snapshot = Marshal.dump classifier1
		#File.open("/home/lalit/Desktop/max/tweetset/config/classifier/snapshot.dat", "w") {|f| f.write(snapshot.force_encoding('UTF-8')) }
		File.open("classifier1.dat", "w") {|f| f.write(classifier_snapshot.force_encoding('UTF-8')) }


		my_input = params[:my_input]
		@inp = "\""+my_input+"\""
		@cat = classifier1.classify @inp
	end
	 

	def t_initial
		correct = params[:correct]
		cinput = params[:cinput]

		if correct.blank?

			data = File.read("classifier1.dat")
			trained_classifier = Marshal.load data
			my_input = params[:my_input]
			@inp = "\""+my_input+"\""
			@cat = trained_classifier.classify @inp
			File.open("training_set.txt", "a+") { |f| f.puts "#{@cat}"+":"+"#{@inp}"}

		else
			@ct = correct
			@inu = cinput

			data = File.read("classifier1.dat")
			trained_classifier = Marshal.load data

			trained_classifier.train("#{@ct}" , "#{@inu}")
			

			classifier_snapshot = Marshal.dump trained_classifier
			#File.open("snapshot.dat", "w") {|f| f.write(snapshot.force_encoding('UTF-8')) }
			File.open("classifier1.dat", "w") {|f| f.write(classifier_snapshot.force_encoding('UTF-8')) }
			@inc = @inu.chomp('"').reverse.chomp('"').reverse
			File.open("training_set.txt", "a+") { |f| f.puts "#{@ct}"+":"+" #{@inc}"}
		end
	end	


	def inp_train
	#	File.open("training_set.txt", "w") { |f| f.puts "#{@cat}"+":"+"#{@inp}/n"}

	end













end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/trainer/index.html.erb
<%= form_tag(train_txt_path, :method => "get", :action => "train_txt") do %>
    <%= text_field_tag :my_input %>
    <%= submit_tag "Send input" %>
<% end %>

  

app/views/trainer/inp_train.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Looks like I'm already well trained.... ;)  </strong>
</p>

app/views/trainer/t_initial.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category</strong>
  <%= @inp %>
  <%= @cat %>
  
</p>

<%= @ct %><br>

<%= @inu %> <br><br><br><br> 



<%= link_to "correct", controller: "trainer", action: "inp_train" %>
<br><br><br><br>


<strong>If incorrect, Give Correct Category</strong>

<%= form_tag(initial_path, :method => "get", :action => "initial") do  %>
   <%= hidden_field_tag(:cinput, @inp) %>
    <%= text_field_tag :correct %>
    <%= submit_tag "Send input" %>
<% end %>

app/views/trainer/train_txt.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category</strong>
  <%= @inp %>
  <%= @cat %>
  
</p>

<%= @ct %><br>

<%= @inu %> <br><br><br><br> 



<%= link_to "correct", controller: "trainer", action: "inp_train" %>
<br><br><br><br>


<strong>If incorrect, Select correct Category</strong>

<%= form_tag(t_initial_path, :method => "get", :action => "inp_train") do  %>
   <%= hidden_field_tag(:cinput, @inp) %>
    <%= text_field_tag :correct %>
    <%= submit_tag "Send input" %>
<% end %>